MVC/CadastroAluno/Models/ErrorViewModel.cs
namespace CadastroAluno.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVC/CadastroAluno/Models/Fruta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroAluno.Models
{
    public class Fruta
    {
        public int Id;

        public string Nome;

        public string Cor;

        public string Categoria;
    }
}

MVC/CadastroAluno/Controllers/FrutasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CadastroAluno.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CadastroAluno.Controllers
{

    public class FrutasController : Controller
    {

        private readonly ILogger<FrutasController> _logger;

        public FrutasController(ILogger<FrutasController> logger)
        {
            _logger = logger;
        }


        // Criar uma lista de frutas
        private static List<Fruta> frutas = new List<Fruta>
{
    new Fruta{Id = 1, Nome = "Maca", Cor = "Vermelho", Categoria = "Tropical"},
    new Fruta{Id = 2, Nome = "Banana", Cor = "Amarelo", Categoria = "Tropical"},
    new Fruta{Id = 3, Nome = "Uva", Cor = "Roxo", Categoria = "Tropical"},
    new Fruta{Id = 4, Nome = "Limao", Cor = "Verde", Categoria = "Citrico"},
    new Fruta{Id = 5, Nome = "Abacaxi", Cor = "Amarelo", Categoria = "Citrico"},


};

        public IActionResult Index()
        {
            return View(frutas);
        }
           [HttpPost]

           
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Create(Fruta fruta)
        {
            fruta.Id = frutas.Max(f => f.Id) + 1;

            frutas.Add(fruta);

            return RedirectToAction("Index");
        }
        public IActionResult FrutasCitricas()
        {
            return View(frutas);
        }
     
        public IActionResult FrutasTropicais()
        {
            return View(frutas);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

MVC/CadastroAluno/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CadastroAluno.Models;

namespace CadastroAluno.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }



public IActionResult QuemSomos()
    {
        return View();
    }


    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/CadastroAluno/Views/Frutas/Create.cshtml
@model CadastroAluno.Models.Fruta

<h1>Cadastro de Fruta</h1>


<form asp-action="Create" method="post">
<label for="">Nome</label>
<input asp-for="Nome">

<label for="">Cor</label>
<input asp-for="Cor">

<label for="">Categoria</label>
<input asp-for="Categoria">

<br>
<buttonclass ="btn btn-success"> Salvar </button>
</form>

MVC/CadastroAluno/Views/Frutas/FrutasCitricas.cshtml
<h1>Pagina de Frutas Citiricas</h1>

MVC/CadastroAluno/Views/Frutas/FrutasTropicais.cshtml
<h1>Pagina de Frutas Tropicais</h1>

MVC/CadastroAluno/Views/Frutas/Index.cshtml
@model List<CadastroAluno.Models.Fruta>

<h1>Pagina de Frutas</h1>
<h2>Lista de frutas</h2>

@foreach ( var fruta in Model ){
<p>
Id: @fruta.Id <br>
Nome: @fruta.Nome <br>
Cor: @fruta.Cor <br>
Categoria: @fruta.Categoria <br>
</p>
   
}

MVC/CadastroAluno/Views/Home/QuemSomos.cshtml
<h1>Pagina Quem somos</h1>

<a asp-controller="Home" asp-action="Index">Voltar pra Home</a>

MVC/CadastroAluno/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt - BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroAluno</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroAluno.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadastroAluno</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Quem Somos">Quem Somos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">    
    <a asp-controller="Frutas" asp-action="Index">Lista Frutas</a>
       <a asp-controller="Frutas" asp-action="Create">Cadastrar Fruta</a>
    <a asp-controller="Frutas" asp-action="FrutasCitricas">Lista Frutas Citricas</a>
    <a asp-controller="Frutas" asp-action="FrutasTropicais">Lista Frutas Tropicais</a>
        <div class="container">
            &copy; 2025 - CadastroAluno - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>